# Пожалуйста, решите следующие задачи

1. Если a = True и b = False, то каким будет вывод следующего выражения: (a and b) or (not a) or (not b)

In [3]:
a = True
b = False
# ваши расчеты
print ((a and b) or (not a) or (not b))

True


2. Если a = True и b = False, то каким будет вывод следующего выражения: (a or b) and (not a) and (not b)

In [4]:
a = True
b = False
# ваши расчеты

3. Для вас задана следующая переменная deg = 91. Решите следующую задачу: если deg > 90, то выведите «тупой угол»

In [5]:
deg = 91
# ваши расчеты

4. Для вас задана следующая переменная deg = 89. Решите следующую задачу: если deg > 90, то выведите «тупой угол», иначе, если deg < 90, выведите «острый угол»

In [6]:
deg = 89
# ваши расчеты

5. Для вас задана следующая переменная deg = 90. Решите следующую задачу: если deg > 90, то выведите «тупой угол», иначе, если deg < 90, выведите «острый угол», иначе выведите «прямой угол»

In [7]:
deg = 90
# ваши расчеты

6. Для вас дан следующий список a = [1, 2, 3, 4, 5, 6, 7]. Пожалуйста, распечатайте список в обратном порядке (пожалуйста, используйте функцию reverse())

In [9]:
a = [1, 2, 3, 4, 5, 6, 7]
# ваши расчеты

7. Для вас дан следующий список a = [1, 2, 3, 4, 5, 6, 7]. Найдите произведение 1) суммы первого и последнего элементов, 2) суммы второго и предпоследнего элементов, 3) суммы третьего и предпоследнего элементов.

In [11]:
a = [1, 2, 3, 4, 5, 6, 7]
# ваши расчеты

8. Для вас дан следующий список a = [1, 2, 3, 4, 5, 5, 4, 5, 3]. Пожалуйста, найдите, сколько раз цифра 3 встречается в этом списке.

In [13]:
 a = [1, 2, 3, 4, 5, 5, 4, 5, 3]
# ваши расчеты

9. Для вас дан следующий список a = [1, 2, 3, 4, 5, 5, 4, 5, 3]. Пожалуйста, очистите этот список, удалив все элементы и распечатайте список

In [15]:
a = [1, 2, 3, 4, 5, 5, 4, 5, 3]
# ваши расчеты

10. Для вас дан следующий список a = [1, 2, 3, 4, 5, 5, 4, 5, 3]. Пожалуйста, добавьте в этот список такие числа, как 100, 101, 102 и распечатайте список

In [7]:
from scipy.stats import norm

# Given data
ARPU_control = 722.46
ARPU_test = 665.74
Standard_Error = 0.347  # Assuming standard error calculated previously

# Calculate the test statistic (Z)
Z = (ARPU_control - ARPU_test) / Standard_Error

# Calculate the p-value using the cumulative distribution function (CDF) of the standard normal distribution
# For a two-tailed test, double the probability obtained from the CDF
p_value = 2 * (1 - norm.cdf(abs(Z)))

print("Test Statistic (Z):", Z)
print("Two-tailed p-value:", p_value)

Test Statistic (Z): 163.45821325648424
Two-tailed p-value: 0.0


In [63]:
list = [1,2,3,4,5]
deleted_item = list.pop()
print (list)

[1, 2, 3, 4]


(1, 3, 6)

In [31]:
import math
math.comb(10, 5)

252

In [40]:
import numpy as np
A = np.array ([[5,-1,1,0],[4,3,12,-6]])
print (np.array([[3],[2]]))
print (A)

[[3]
 [2]]
[[ 5 -1  1  0]
 [ 4  3 12 -6]]


In [39]:
A[0,2] = 8
print (A)

[[ 5 -1  8  0]
 [ 4  3 12 -6]]


In [54]:
x = np.linspace (-2,4,9)
print (x)

[-2.   -1.25 -0.5   0.25  1.    1.75  2.5   3.25  4.  ]


In [58]:
def zip_(list1, list2):
    combined_list = []
    min_length = min(len(list1), len(list2))  # Determine the shorter length between list1 and list2
    
    for i in range(min_length):
        combined_list.append((list1[i], list2[i]))  # Append tuple of corresponding elements from list1 and list2
    
    return combined_list

# Define lists
list1 = [1, 5, 3, 8, 35]
list2 = [2, 7, 9]

# Call the function
result = zip_(list1, list2)
print(result)

[(1, 2), (5, 7), (3, 9)]


In [66]:
my_tuple = (1,3,6)
my_tuple

len(my_tuple+ (1,3, 'aaa'))

6

In [67]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random
import statistics




In [68]:
sample_data = (1,2,3,3,3,5,7,8,8,9,10)
np.mean(sample_data)

5.363636363636363