1) number of rooms
2) age of the apartment
3) area: a) Bostandyq, b) Medeu, c) Auezov

$x_{1}$ = number of rooms \
$x_{2}$ = age of the apartment \
$x_{3}$ = area

if area == "Bostandyq": return [1, 0, 0] \
if area == "Medeu": return [0, 1, 0] \
if area == "Auezov": return [0, 0, 1]

$x^{(1)}$ = [2, 1995, 1, 0, 0] \
$x^{(2)}$ = [3, 1991, 0, 1, 0] \
$x^{(3)}$ = [4, 2022, 0, 0, 1] 

In [3]:
import numpy as np

x1 = np.array([2, 1995, 1, 0, 0])
x2 = np.array([3, 1991, 0, 1, 0])
x3 = np.array([4, 2022, 0, 0, 1])

X = np.array([x1, x2, x3])
y = np.array([100, 99, 150])

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)
print(X_train)
print(X_test)
print(y_train)
print(y_test)

[[   2 1995    1    0    0]
 [   4 2022    0    0    1]]
[[   3 1991    0    1    0]]
[100 150]
[99]
