In [1]:
import numpy as np

X = np.array([np.array([1, 0, 1]), 
             np.array([0, 0, 1]),
             np.array([1, 1, 0]),
             np.array([1, 1, 1])])
y = np.array([0, 0, 1, 1])

print(X.shape, y.shape)

(4, 3) (4,)


In [2]:
X = np.array([np.array([1, 0, 1]), 
             np.array([0, 0, 1]),
             np.array([1, 1, 0]),
             np.array([1, 1, 1])])

In [3]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)
print(X_train)
print(X_test)
print(y_train)
print(y_test)

[[1 1 0]
 [1 1 1]]
[[1 0 1]
 [0 0 1]]
[1 1]
[0 0]


In [27]:
y_pred = [0, 1]

In [28]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

0.5


In [29]:
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred)
print(precision)

0.0


In [34]:
from sklearn.metrics import recall_score

recall = recall_score(y_test, y_pred, zero_division=0)
print(recall)

0.0


In [32]:
from sklearn.metrics import f1_score

f1 = f1_score(y_test, y_pred)
print(f1)

0.0
