https://www.kaggle.com/datasets/dragonheir/logistic-regression

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

df = pd.read_csv('Social_Network_Ads.csv')

print(df.to_string())

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
5    15728773    Male   27            58000          0
6    15598044  Female   27            84000          0
7    15694829  Female   32           150000          1
8    15600575    Male   25            33000          0
9    15727311  Female   35            65000          0
10   15570769  Female   26            80000          0
11   15606274  Female   26            52000          0
12   15746139    Male   20            86000          0
13   15704987    Male   32            18000          0
14   15628972    Male   18            82000          0
15   15697686    Male   29            80000          0
16   15733883    Male   47            25000          1
17   15617

In [2]:
print("Number of missing data in every columns: ")
df.isna().sum()

Number of missing data in every columns: 


User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [3]:
print("Number of duplicated data in every columns: ",df.duplicated().sum())

Number of duplicated data in every columns:  0


In [4]:
df[['Age','EstimatedSalary']].describe().T

count       mean           std      min       25%      50%  \
Age              400.0     37.655     10.482877     18.0     29.75     37.0   
EstimatedSalary  400.0  69742.500  34096.960282  15000.0  43000.00  70000.0   

                     75%       max  
Age                 46.0      60.0  
EstimatedSalary  88000.0  150000.0

In [5]:
df['Gender'] = df['Gender'].replace(['Male'], 1)
df['Gender'] = df['Gender'].replace(['Female'], 0)

In [6]:
print(df.to_string())

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510       1   19            19000          0
1    15810944       1   35            20000          0
2    15668575       0   26            43000          0
3    15603246       0   27            57000          0
4    15804002       1   19            76000          0
5    15728773       1   27            58000          0
6    15598044       0   27            84000          0
7    15694829       0   32           150000          1
8    15600575       1   25            33000          0
9    15727311       0   35            65000          0
10   15570769       0   26            80000          0
11   15606274       0   26            52000          0
12   15746139       1   20            86000          0
13   15704987       1   32            18000          0
14   15628972       1   18            82000          0
15   15697686       1   29            80000          0
16   15733883       1   47            25000          1
17   15617

In [7]:
import numpy as np

df_x = df[['Gender', 'Age', 'EstimatedSalary']]
df_y = df[['Purchased']]
X = df_x.values
y = df_y.values
print(X)
print(y)

[[    1    19 19000]
 [    1    35 20000]
 [    0    26 43000]
 ...
 [    0    50 20000]
 [    1    36 33000]
 [    0    49 36000]]
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0

In [8]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler() 
X_scaled = ss.fit_transform(X) 

In [9]:
X_scaled_train, X_scaled_test, y_scaled_train, y_scaled_test = train_test_split(X_scaled, y,train_size=0.33)

In [10]:
from sklearn.linear_model import LogisticRegression

log = LogisticRegression()
log.fit(X_scaled_train, y_scaled_train)

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [11]:
y_pred = log.predict(X_scaled_test)

In [12]:
from sklearn.metrics import accuracy_score

acc = accuracy_score(y_scaled_test, y_pred) * 100
print(acc)

83.2089552238806


In [13]:
print(f"h(x) = {log.intercept_} + [{log.coef_[0][0]}] X1 + [{log.coef_[0][1]}] X2 + [{log.coef_[0][2]}] X3")

h(x) = [-1.00009547] + [0.13403965485392053] X1 + [1.805786554923369] X2 + [1.176433412098122] X3


In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y,train_size=0.33,random_state=42)

In [15]:
log = LogisticRegression()
log.fit(X_train, y_train)

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [16]:
y_pred = log.predict(X_scaled_test)

In [17]:
from sklearn.metrics import accuracy_score

acc = accuracy_score(y_test, y_pred) * 100
print(acc)

61.940298507462686
